### ISSUE TITLE
(SP - m6l2b) crash after train passing by

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#199] opened 2024-02-07 17:16 UTC
Got a crash few seconds after train passed by me... There was an autosave that time... maybe the trigger for the crash?

```
z:         $track_guards ai_on
Autosaved with set 1
Saving to m6l2b0001...
SV_ArchiveLevelFile()
----- Client Shutdown (Received signal 11) -----
Channel memory manager started
------ Unloading ClientGame ------
Channel memory manager started
Closing SDL audio playback device...
SDL audio playback device closed.
SDL audio shut down.
RE_Shutdown( 1 )
-----------------------
----- Server Shutdown (Received signal 11) -----
==== ShutdownGame ====
------ Unloading Game ------
```

**Comment by gbudny** [comment] 2024-06-02 20:58
Hi

I remember I had this bug on Linux, but it was fixed by you a few months ago. I don't know if it works on Windows.

**Comment by smallmodel** [comment] 2024-06-03 18:18
I can't reproduce the crash either

**Closed** 2024-06-03 18:18 UTC
Labels: client, server, single-player
