### ISSUE TITLE
(BT) crash when closing dedicated server console

### ISSUE THREAD

**Issue by bulldozerecske** [openmoh/openmohaa#466] opened 2024-10-23 05:58 UTC
Not sure if it is because of the same reason as #458.

The map has been loaded while I realized I had forgotten to disable dedicated option in start_game menu. After that I closed the console.

![image](https://github.com/user-attachments/assets/d418d23c-36c7-4a55-9fa6-5d35ce4cf7bc)

Version: OpenMoHAA 0.71.0-unstable+187.de1d3b6 win_msvc64-x86_64 Oct 22 2024 UTC

**Comment by smallmodel** [comment] 2024-10-23 19:21
yeah it has to be fixed upstream in ioq3, the problem is the race condition occurring when closing the window console on Windows, should type `quit` instead

**Closed by smallmodel** 2024-10-23 19:21 UTC
